### ISSUE TITLE
NullPointerException at com.thebluealliance.androidclient.fragments.event.EventDistrictPointsFragment.updateDistrict

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#276]
As mentioned in Issue #274 , TBA app crashed when I tapped the phone's Back button a few times. From logcat:

```
11-08 11:08:09.510      764-819/? W/PackageManager﹕ Unknown permission com.thebluealliance.androidclient.permission.C2D_MESSAGE in package com.thebluealliance.androidclient
11-08 11:08:17.910      764-819/? W/PackageManager﹕ Unknown permission com.thebluealliance.androidclient.permission.C2D_MESSAGE in package com.thebluealliance.androidclient
11-08 11:33:46.550      764-822/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 11:33:48.840    764-14687/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 11:33:50.690    764-14687/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 11:33:53.140     764-1200/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 11:33:54.050     764-1118/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 11:33:56.840     764-3327/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 11:33:58.990    764-14687/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 11:34:00.240     764-1117/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 11:34:02.370    764-10547/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 11:40:26.280     764-1117/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,459][1080,651] (has extras) }
11-08 11:43:29.570     764-1117/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,276][1080,468] (has extras) }
11-08 11:43:47.170    764-17894/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,447][1080,639] (has extras) }
11-08 11:44:09.290     764-1200/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,977][1080,1169] (has extras) }
11-08 11:49:12.620     764-1028/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,1022][1080,1214] (has extras) }
11-08 11:53:06.620    764-10547/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,602][1080,794] (has extras) }
11-08 11:55:11.330    764-14688/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,773][1080,965] (has extras) }
11-08 12:23:01.930    2356-2356/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.thebluealliance.androidclient, PID: 2356
    java.lang.NullPointerException
            at com.thebluealliance.androidclient.fragments.event.EventDistrictPointsFragment.updateDistrict(EventDistrictPointsFragment.java:128)
            at com.thebluealliance.androidclient.background.event.PopulateEventDistrictPoints$1.run(PopulateEventDistrictPoints.java:71)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
11-08 12:40:12.730     764-1118/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,493][1080,685] (has extras) }
11-08 12:40:26.470     764-1117/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,429][1080,621] (has extras) }
11-08 12:40:33.800     764-3327/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 12:40:33.810      764-822/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 12:40:34.920     764-1201/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 12:40:35.590     764-1117/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 12:40:37.980    764-14688/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 12:40:37.990     764-1201/? E/NotificationService﹕ Package has already posted 50 notifications.  Not showing more.  package=com.thebluealliance.androidclient
11-08 12:40:38.170    764-17894/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,429][1080,621] (has extras) }
11-08 12:40:52.360    764-10514/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,429][1080,621] (has extras) }
11-08 12:44:15.880    764-14688/? W/ActivityManager﹕ startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.thebluealliance.androidclient/.activities.ViewMatchActivity bnds=[0,429][1080,621] (has extras) }
```

**Comment by phil-lopreiato** [comment]
Fixed in 48d8195
