### ISSUE TITLE
Populate District Points NPE

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#308]
From crash report:
```
java.lang.NullPointerException
at com.thebluealliance.androidclient.fragments.event.EventDistrictPointsFragment.updateDistrict(EventDistrictPointsFragment.java:128)
at com.thebluealliance.androidclient.background.event.PopulateEventDistrictPoints$1.run(PopulateEventDistrictPoints.java:71)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5633)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by phil-lopreiato** [comment]
Reported for v1.4. Already fixed in 48d81952
