### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#333]
```
Stacktrace:
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
at com.google.gson.JsonParser.parse(JsonParser.java:65)
at com.google.gson.JsonParser.parse(JsonParser.java:45)
at com.thebluealliance.androidclient.background.firstlaunch.LoadAllData.doInBackground(LoadAllData.java:114)
at com.thebluealliance.androidclient.background.firstlaunch.LoadAllData.doInBackground(LoadAllData.java:33)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1572)
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1421)
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:544)
at com.google.gson.stream.JsonReader.peek(JsonReader.java:427)
at com.google.gson.JsonParser.parse(JsonParser.java:60)
```

**Comment by phil-lopreiato** [comment]
Did this happen to you? Can you reproduce it and get the json text it's failing on?

**Comment by fangeugene** [comment]
No, got an email.

On 2/26/15, Phil Lopreiato <notifications@github.com> wrote:
> Did this happen to you? Can you reproduce it and get the json text it's
> failing on?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/the-blue-alliance/the-blue-alliance-android/issues/333#issuecomment-76311581


-- 
-Eugene

**Comment by phil-lopreiato** [comment]
Google Play also has this stack trace. Probably related...
```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
at com.google.gson.JsonParser.parse(JsonParser.java:65)
at com.google.gson.JsonParser.parse(JsonParser.java:45)
at com.thebluealliance.androidclient.datafeed.JSONManager.getasJsonObject(JSONManager.java:59)
at com.thebluealliance.androidclient.models.Event.getStats(Event.java:145)
at com.thebluealliance.androidclient.datafeed.DataManager$Events.getEventStats(DataManager.java:315)
at com.thebluealliance.androidclient.datafeed.DataManager$Events.getEventStats(DataManager.java:306)
at com.thebluealliance.androidclient.background.event.PopulateEventInfo.doInBackground(PopulateEventInfo.java:126)
at com.thebluealliance.androidclient.background.event.PopulateEventInfo.doInBackground(PopulateEventInfo.java:42)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1572)
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1421)
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:544)
at com.google.gson.stream.JsonReader.peek(JsonReader.java:427)
at com.google.gson.JsonParser.parse(JsonParser.java:60)
... 12 more
```
