### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#338]
Something with back stack...
```
java.lang.IndexOutOfBoundsException: Invalid index 4, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.set(ArrayList.java:481)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1087)
at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1223)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:709)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
at android.os.Handler.handleCallback(Handler.java)
at android.os.Handler.dispatchMessage(Handler.java)
at android.os.Looper.loop(Looper.java)
at android.app.ActivityThread.main(ActivityThread.java)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

**Comment by phil-lopreiato** [comment]
No idea where this is being thrown. Anybody have ideas?

**Comment by Adam8234** [comment]
Something that was added recently? That's seems like that would be a good
place to find the issue.

**Comment by phil-lopreiato** [comment]
It's been kicking around here and there for a little while. Here's the reports from the Play Store console
![screenshot from 2015-03-09 14 46 26](https://cloud.githubusercontent.com/assets/2754863/6561921/25087b30-c66b-11e4-9ad2-c81cf677c4b0.png)

**Comment by Adam8234** [comment]
It's definitely not a 4.X thing. I see that someone made a somewhat useful
comment. Maybe try spamming through the navigation drawer and menus?

**Comment by phil-lopreiato** [comment]
Still can't reproduce it... If anybody else can, post here, I guess

**Comment by tanis7x** [comment]
Check out the last line- `at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)`. It looks like this is caused by a bug in Xposed, which means these are rooted users toying with their devices.

[FDroid had a potentially similar issue](https://gitlab.com/fdroid/fdroidclient/issues/152), and the cause of the clash with Xposed appears to have been missing translations for a string array. I'm skeptical of that being our issue though.

**Comment by phil-lopreiato** [comment]
Good catch, although I just checked the console, and there are two other reports of the same crash that don't mention xposed. Seems like it's our issue, but it still doesn't say where. Sadly, Google Analytics doesn't give a more detailed trace, either.

```
java.lang.IndexOutOfBoundsException: Invalid index 4, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.set(ArrayList.java:481)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1087)
at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1223)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:709)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5097)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by 1fish2** [comment]
There's no TBA code in that stack trace. So I'm thinking the app might've set up some malformed state (including resources) which FragmentManagerImpl trips over without sanity checking, or else makes a call that delegates work to another thread that trips.

Google finds this [SO question](http://stackoverflow.com/questions/22521412/getting-exception-indexoutofboundsexception-fragmentmanagerimpl-after-sharing-so) with such a stack trace, also Issue #300 , and a similar [SO question](http://stackoverflow.com/questions/21709107/why-does-popbackstack-call-oncreateview-of-the-fragment) with the topical clue

> when you pop a fragment, fragment manager tries to recreate a previous view to display it

**Comment by phil-lopreiato** [comment]
Haven't seen this one in a while, so I'm going to assume it's fixed. Will reopen if it appears again
