### ISSUE TITLE
App crashes after myTBA Settings screen

### ISSUE THREAD

**Issue by organizefish** [the-blue-alliance/the-blue-alliance-android#343]
Have attempted to install the app on three different phones: HTC One, HTC One M8, and a Samsung Galaxy S3. After the downloading data occurs, from the myTBA Settings screen, the app crashes upon all following options:
- Google+ Sign In
- Google+ Sign In with alternate permissions selected
- Not Now

**Comment by phil-lopreiato** [comment]
This is really odd - not something I've ever seen. What versions of android do the phones run? Is you're phone rooted/use some permission blocker? 

Can you get a stack trace to us somehow? By either hitting 'report' on the dialog, or by connecting your phone, enabling USB debugging, and running 'adb logcat' 

Sorry of you've already reported the crash, the Google Play console is a pain to use on my phone

**Comment by fangeugene** [comment]
Also, what app version are you running?

**Comment by phil-lopreiato** [comment]
Here's the stack trace. Doesn't look good
```
java.lang.NoClassDefFoundError: android/os/PersistableBundle
at java.lang.Class.getDeclaredMethods(Native Method)
at java.lang.Class.getDeclaredMethods(Class.java:656)
at de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:71)
at de.greenrobot.event.EventBus.register(EventBus.java:163)
at de.greenrobot.event.EventBus.register(EventBus.java:133)
at com.thebluealliance.androidclient.activities.RefreshableHostActivity.onResume(RefreshableHostActivity.java:83)
at com.thebluealliance.androidclient.activities.HomeActivity.onResume(HomeActivity.java:158)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1198)
at android.app.Activity.performResume(Activity.java:5618)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3059)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3098)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2469)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5653)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.PersistableBundle" on path: DexPathList[[zip file "/data/app/com.thebluealliance.androidclient-5.apk"],nativeLibraryDirectories=[/data/app-lib/com.thebluealliance.androidclient-5, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
... 22 more
```

**Comment by phil-lopreiato** [comment]
Appears to be a [bug in EventBus](https://github.com/greenrobot/EventBus/issues/156)

**Comment by phil-lopreiato** [comment]
Issue is probably with [this commit] (https://github.com/the-blue-alliance/the-blue-alliance-android/commit/75cc73b2d00a8574ff41b00584b7b40b8c52e3d8),  uses a android v21 version of onCreate
