### ISSUE TITLE
NPE crash on a non-existent event

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#386]
This case shouldn't arise in the field so I'll just log it and fix the test data in `test_notification.py` in #379 where the test `schedule_updated` push notification uses the non-existent Event "2014ausy" event. (Why didn't this crash before?)

`PopulateEventInfo#onPostExecute()` calls `Event#getDateString()` expecting a non-null value but `getDateString()` can catch `FieldNotDefinedException` and return `null`.

**Test case 1:** Uninstall the debug app. Sync to the master branch. Optionally set a breakpoint in the `Event#getDateString()` catch for `FieldNotDefinedException`. Launch the debug build. Let it load team & event data. Tap "not now" for myTBA sign in. It will hit the breakpoint (8 times IIRC) in `Event#getDateString()` as called by `Event#render()`. This breakpoint on the background thead seems to make it hang.

**Test case 2:** Repeat test case 1 but don't set a breakpoint. (It's puzzling that "Missing fields for getting date string" is not in logcat given that it would've hit the breakpoint. Is the debugger wrong about what happens in the background thread?) Then send a test notification for a non-existent event like "2014ausy". Then tap that notification to go to the Event screen. That's when `PopulateEventInfo#onPostExecute()` calls `Event#getDateString()`, gets a `null` result, then crashes with a NPE. (See logcat below.)

**Question:** Should `Event#getDateString()` propagate the `FieldNotDefinedException`? Return `""`? Should `PopulateEventInfo#onPostExecute()` cope with the `null` result?

```
04-09 18:04:00.241    6738-6738/com.thebluealliance.androidclient.development E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.thebluealliance.androidclient.development, PID: 6738
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
            at com.thebluealliance.androidclient.background.event.PopulateEventInfo.onPostExecute(PopulateEventInfo.java:207)
            at com.thebluealliance.androidclient.background.event.PopulateEventInfo.onPostExecute(PopulateEventInfo.java:43)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
04-09 18:04:00.246    6738-7404/com.thebluealliance.androidclient.development E/tba-android:dataManager﹕ Error: HTTP 404
    {"404": "2014ausy event not found"}
    from fetching http://www.thebluealliance.com/api/v2/event/2014ausy/awards

...

04-09 18:04:04.217    6738-7401/com.thebluealliance.androidclient.development E/tba-android:dataManager﹕ Error: HTTP 404
    {"404": "2014ausy event not found"}
    from fetching http://www.thebluealliance.com/api/v2/event/2014ausy/stats
04-09 18:04:04.217    6738-7401/com.thebluealliance.androidclient.development D/tba-android:dataManager﹕ updated in db? false
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ com.thebluealliance.androidclient.models.BasicModel$FieldNotDefinedException: Field Database.Events.STATS is not defined
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at com.thebluealliance.androidclient.models.Event.getStats(Event.java:148)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at com.thebluealliance.androidclient.datafeed.DataManager$Events.getEventStats(DataManager.java:308)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at com.thebluealliance.androidclient.datafeed.DataManager$Events.getEventStats(DataManager.java:299)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at com.thebluealliance.androidclient.background.event.PopulateEventStats.doInBackground(PopulateEventStats.java:70)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at com.thebluealliance.androidclient.background.event.PopulateEventStats.doInBackground(PopulateEventStats.java:44)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
04-09 18:04:04.218    6738-7401/com.thebluealliance.androidclient.development W/tba-android﹕ unable to load event stats
04-09 18:04:06.479    6738-6738/com.thebluealliance.androidclient.development I/Process﹕ Sending signal. PID: 6738 SIG: 9
04-09 18:04:06.511    2245-2366/? I/WindowState﹕ WIN DEATH: Window{2d700b39 u0 com.thebluealliance.androidclient.development/com.thebluealliance.androidclient.activities.ViewEventActivity}
04-09 18:04:06.591    2245-4694/? I/ActivityManager﹕ Process com.thebluealliance.androidclient.development (pid 6738) has died
```

**Comment by IAmAGitNewbie** [comment]
What would be the consequences of returning "" instead of null in failures cases like this?

**Comment by 1fish2** [comment]
That case handles `""` and will crash on `null`.

The EventListElement constructor stores `mEventDates = event.getDateString()` and the resulting instance gets serialized (and stored in the local DB, presumably), so a null can bite later.
