### ISSUE TITLE
Team Media Fragment NPE

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#408]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.thebluealliance.androidclient/com.thebluealliance.androidclient.activities.ViewTeamActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeAllViews()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2728)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5837)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeAllViews()' on a null object reference
at com.thebluealliance.androidclient.fragments.team.TeamMediaFragment.onRefreshStart(TeamMediaFragment.java:90)
at com.thebluealliance.androidclient.activities.RefreshableHostActivity.startRefresh(RefreshableHostActivity.java:175)
at com.thebluealliance.androidclient.activities.RefreshableHostActivity.onCreate(RefreshableHostActivity.java:40)
at com.thebluealliance.androidclient.activities.FABNotificationSettingsActivity.onCreate(FABNotificationSettingsActivity.java:75)
at com.thebluealliance.androidclient.activities.ViewTeamActivity.onCreate(ViewTeamActivity.java:79)
at android.app.Activity.performCreate(Activity.java:6221)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
... 10 more
```

**Comment by nwalters512** [comment]
None of this code even exists any more and we haven't encountered any similar issues recently. Marking as resolved.
