### ISSUE TITLE
JsonNull error when loading team@event without stats on appv3-datafeed branch

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#475]
```
09-18 19:32:10.752    6512-6512/com.thebluealliance.androidclient.development E/tba-android﹕ java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject
            at com.thebluealliance.androidclient.datafeed.maps.TeamStatsExtractor.call(TeamStatsExtractor.java:7)
            at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
            at rx.observers.SerializedObserver.onNext(SerializedObserver.java:95)
            at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
            at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onNext(OperatorConcat.java:206)
            at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
            at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe$2.onResponse(RxJavaCallAdapterFactory.java:109)
            at retrofit.OkHttpCall$1.callSuccess(OkHttpCall.java:77)
            at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:95)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.google.gson.JsonNull.class
            at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
            at rx.observers.SerializedObserver.onNext(SerializedObserver.java:95)
            at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:95)
            at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onNext(OperatorConcat.java:206)
            at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
            at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe$2.onResponse(RxJavaCallAdapterFactory.java:109)
            at retrofit.OkHttpCall$1.callSuccess(OkHttpCall.java:77)
            at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:95)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by phil-lopreiato** [comment]
Whoops, must have missed one :P
