### ISSUE TITLE
Redownload data causes errors with event list rendering

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#486]
While trying to fix #471, I ran into a rather weird issue. It seems as though that process throws the app into some sort of invalid state that causes the rendering of the main event lists to fail. Failure occurs across all years and is isolated to the top-level event lists; event lists within team views and event views themselves still function normally.

Here is the offending stacktrace:

```
E/tba-android: UNABLE TO RENDER
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
W/System.err:     at com.thebluealliance.androidclient.adapters.BindableFragmentPagerAdapter.setAutoBindOnceAtPosition(BindableFragmentPagerAdapter.java:38)
 W/System.err:     at com.thebluealliance.androidclient.fragments.EventsByWeekFragment.updateLabels(EventsByWeekFragment.java:130)
 W/System.err:     at com.thebluealliance.androidclient.binders.EventTabBinder.updateData(EventTabBinder.java:23)
 W/System.err:     at com.thebluealliance.androidclient.binders.EventTabBinder.updateData(EventTabBinder.java:10)
 W/System.err:     at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber.lambda$bindData$33(BaseAPISubscriber.java:132)
 W/System.err:     at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber.access$lambda$2(BaseAPISubscriber.java)
 W/System.err:     at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber$$Lambda$3.call(Unknown Source)
 W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
 W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
 W/System.err:     at android.os.Looper.loop(Looper.java:148)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I tested the redownload process when I was first implementing it, so either I suck at testing, this is some weird edge case, or there's been a regression somewhere.

**Comment by phil-lopreiato** [comment]
Weiiird. It might be related to https://github.com/the-blue-alliance/the-blue-alliance-android/commit/75318c9dc708ba7377ea6aeab045f7a951ea0b35 (moving onboarding to the new datafeed)
