### ISSUE TITLE
Event rankings can't handle "###B" team numbers

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#530]
Reported on the Play Dev Console:

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NumberFormatException: Invalid int: "3324B"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parse(Integer.java:410)
	at java.lang.Integer.parseInt(Integer.java:367)
	at java.lang.Integer.parseInt(Integer.java:334)
	at com.google.gson.JsonPrimitive.getAsInt(JsonPrimitive.java:260)
	at com.thebluealliance.androidclient.background.event.PopulateEventRankings.doInBackground(PopulateEventRankings.java:109)
	at com.thebluealliance.androidclient.background.event.PopulateEventRankings.doInBackground(PopulateEventRankings.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
```

From the user:
```
Everytime I go to watch the CORI offseason event and click on it, it says TBA has stopped working
```

**Comment by phil-lopreiato** [comment]
This is an old trace, but we should still double check and make sure we're correctly handling multi-team keys

**Comment by nwalters512** [comment]
Already submitted the PR :)
