### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#534]
From Play Store:

```
java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder
	at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:642)
	at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:2868)
	at android.support.v7.widget.ToolbarWidgetWrapper.getMenu(ToolbarWidgetWrapper.java:694)
	at android.support.v7.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:578)
	at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:436)
	at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by nwalters512** [comment]
Lol, I was wondering how long it would be before we saw this bug. This is a widespread issue caused by Samsung including a different version of the support lib in the classpath on all their 4.2 builds. I think the fix was something with Proguard, I'll look it up again.

**Comment by phil-lopreiato** [comment]
Solution can be found here: http://stackoverflow.com/questions/24809580/noclassdeffounderror-android-support-v7-internal-view-menu-menubuilder
