### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance-android#562]
```
Version: 3.0.5
Stacktrace:
java.lang.RuntimeException: java.net.SocketTimeoutException: failed to connect to www.thebluealliance.com/104.27.142.180 (port 443) after 10000ms
at rx.observables.BlockingObservable.first(BlockingObservable.java:1455)
at com.thebluealliance.androidclient.background.firstlaunch.LoadTBAData.doInBackground(LoadTBAData.java:86)
at com.thebluealliance.androidclient.background.firstlaunch.LoadTBAData.doInBackground(LoadTBAData.java:32)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketTimeoutException: failed to connect to www.thebluealliance.com/104.27.142.180 (port 443) after 10000ms
at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
at libcore.io.IoBridge.connect(IoBridge.java:122)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
at java.net.Socket.connect(Socket.java:882)
at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:190)
at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:14196)
at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:2328)
at com.squareup.okhttp.Call.getResponse(Call.java:267)
at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
at com.thebluealliance.androidclient.datafeed.APIv2RequestInterceptor.intercept(APIv2RequestInterceptor.java:45)
at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
at com.squareup.okhttp.Call.access$100(Call.java:34)
at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
... 3 more
```

**Comment by phil-lopreiato** [comment]
Argh...

That whole code chuck uses a `BlockingObservable` in an `AsyncTasks` that's in a massive `try`/`catch` block that catches all `Exceptions`. Not sure why it isn't accounting for this....
