### ISSUE TITLE
NoClassDefFoundError is back

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#564]
Alternate title: Dammit Samsung

This should have been fixed in https://github.com/the-blue-alliance/the-blue-alliance-android/commit/8840d7883bafa6bd1476f7d578a47b013c826a86, but it's still appearing on version 3.0.5, which should have included this fix.

```
java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder
	at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:642)
	at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:868)
	at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:839)
	at android.support.v7.widget.ToolbarWidgetWrapper.getMenu(ToolbarWidgetWrapper.java:694)
	at android.support.v7.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:578)
	at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:436)
	at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5285)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by phil-lopreiato** [comment]
Whyyyy
/headdesk

**Comment by phil-lopreiato** [comment]
Looks like there are some changes with supportlib v23

```
#FOR APPCOMPAT 23.1.1:
-keep class !android.support.v7.view.menu.*MenuBuilder*, android.support.v7.** { *; }
-keep interface android.support.v7.* { *; }
```

http://stackoverflow.com/a/34895791
