### ISSUE TITLE
ListViewBinder throws exception when it tries to access ListView

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#565]
I've only seen this behavior with the main teams list. When the lists come back into the foreground and we attempt to bind new data to them, we get a ton of these exceptions. The easy solution would just be to check if the list is null before accessing it, but the real question is why is the list null in the first place? The binder should be able to hold on to the reference to the ListView even when it goes into the background and then comes back into the foreground.

```
02-22 17:58:09.679 12892-12892/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setVisibility(int)' on a null object reference
02-22 17:58:09.679 12892-12892/? W/System.err:     at com.thebluealliance.androidclient.binders.ListViewBinder.bindNoDataView(ListViewBinder.java:97)
02-22 17:58:09.679 12892-12892/? W/System.err:     at com.thebluealliance.androidclient.binders.ListViewBinder.onComplete(ListViewBinder.java:79)
02-22 17:58:09.679 12892-12892/? W/System.err:     at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber.lambda$onCompleted$37(BaseAPISubscriber.java:119)
02-22 17:58:09.679 12892-12892/? W/System.err:     at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber.access$lambda$0(BaseAPISubscriber.java)
02-22 17:58:09.679 12892-12892/? W/System.err:     at com.thebluealliance.androidclient.subscribers.BaseAPISubscriber$$Lambda$1.call(Unknown Source)
02-22 17:58:09.679 12892-12892/? W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
02-22 17:58:09.679 12892-12892/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
02-22 17:58:09.680 12892-12892/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-22 17:58:09.680 12892-12892/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
02-22 17:58:09.680 12892-12892/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
02-22 17:58:09.680 12892-12892/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-22 17:58:09.680 12892-12892/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-22 17:58:09.680 12892-12892/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by phil-lopreiato** [comment]
Is ButterKnife bound? Maybe it gets unbound here on fragment pause?

**Comment by nwalters512** [comment]
I checked, we only unbind from ButterKnife when the fragment's view is destroyed, and it doesn't look like that's happening.
