### ISSUE TITLE
Fix Event Next/Last Match

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#585]
Shouldn't have this case...
![screenshot_20160227-180856](https://cloud.githubusercontent.com/assets/2754863/13380398/16647e40-de10-11e5-87bd-d422626d3c80.png)

**Comment by phil-lopreiato** [comment]
May relate to the following stack traces:
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5466)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at com.thebluealliance.androidclient.binders.EventInfoBinder.lambda$onEvent$35(EventInfoBinder.java:248)
	at com.thebluealliance.androidclient.binders.EventInfoBinder.access$lambda$1(EventInfoBinder.java)
	at com.thebluealliance.androidclient.binders.EventInfoBinder$$Lambda$2.call(Unknown Source)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
```

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setVisibility(int)' on a null object reference
	at com.thebluealliance.androidclient.binders.EventInfoBinder.showLastMatch(EventInfoBinder.java:216)
	at com.thebluealliance.androidclient.binders.EventInfoBinder.lambda$onEvent$34(EventInfoBinder.java:233)
	at com.thebluealliance.androidclient.binders.EventInfoBinder.access$lambda$0(EventInfoBinder.java)
	at com.thebluealliance.androidclient.binders.EventInfoBinder$$Lambda$1.call(Unknown Source)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 8 more
```
