### ISSUE TITLE
OutOfMemoryError with large Bitmaps

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#588]
It looks like assuming that everyone has large amount of available RAM is a bad idea. Who would have thought?

The relevant bitmaps from the two stack traces we have are the Blue Alliance "blue rays" background that's used on wearables and the default header in the navigation drawer.

Relevant crashes:

```
java.lang.OutOfMemoryError: Failed to allocate a 1102512 byte allocation with 646944 free bytes and 631KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:467)
	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:497)
	at com.thebluealliance.androidclient.gcm.notifications.BaseNotification.getBaseBuilder(BaseNotification.java:136)
	at com.thebluealliance.androidclient.gcm.notifications.BaseNotification.getBaseBuilder(BaseNotification.java:147)
	at com.thebluealliance.androidclient.gcm.notifications.ScoreNotification.buildNotification(ScoreNotification.java:211)
	at com.thebluealliance.androidclient.gcm.GCMMessageHandler.handleMessage(GCMMessageHandler.java:163)
	at com.thebluealliance.androidclient.gcm.GCMMessageHandler.onHandleIntent(GCMMessageHandler.java:97)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

```
java.lang.OutOfMemoryError: Failed to allocate a 5760012 byte allocation with 1818992 free bytes and 1776KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2477)
	at android.content.res.Resources.loadDrawable(Resources.java:2384)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
	at android.widget.ImageView.<init>(ImageView.java:156)
	at android.widget.ImageView.<init>(ImageView.java:145)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:58)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:54)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:95)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:938)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:992)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:180)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at com.thebluealliance.androidclient.fragments.NavigationDrawerFragment.onCreateView(NavigationDrawerFragment.java:140)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1036)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1226)
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1328)
	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2284)
	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:111)
	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:314)
	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
	at com.thebluealliance.androidclient.activities.NavigationDrawerActivity.onCreate(NavigationDrawerActivity.java:72)
	at com.thebluealliance.androidclient.activities.BaseActivity.onCreate(BaseActivity.java:59)
	at com.thebluealliance.androidclient.activities.DatafeedActivity.onCreate(DatafeedActivity.java:46)
	at com.thebluealliance.androidclient.activities.MyTBASettingsActivity.onCreate(MyTBASettingsActivity.java:85)
	at com.thebluealliance.androidclient.activities.TeamAtEventActivity.onCreate(TeamAtEventActivity.java:57)
	at android.app.Activity.performCreate(Activity.java:6010)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.access$800(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
```

**Comment by phil-lopreiato** [comment]
Funny how that works...

Android docs to the rescue!
http://developer.android.com/training/displaying-bitmaps/load-bitmap.html

**Comment by fangeugene** [comment]
Is there a reason the "blue rays" image has to be that large?

**Comment by nwalters512** [comment]
Nope, it's mostly going to be displayed on watch screens of at most about 400x400 pixels. We could definitely shrink it a bit, or even just use a flat blue background. I've never seen how our notifications actually look on a wearable.

**Comment by nwalters512** [comment]
The rays look nice, though we could probably just use a blue background. Also, it's a good thing I checked how stuff looks.. the summary notification looks awful on Wear, I'll file an issue for that.
