### ISSUE TITLE
[imgur uploads] Handle Filesystem Errors

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance-android#642]
```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: rx.exceptions.OnErrorNotImplementedException: failed to rename /data/data/com.thebluealliance.androidclient/cache/592a78e7b824550f7b0768ef84481c59.0.tmp to /data/data/com.thebluealliance.androidclient/cache/592a78e7b824550f7b0768ef84481c59.0
	at rx.Observable$27.onError(Observable.java:7535)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 9 more
Caused by: java.io.IOException: failed to rename /data/data/com.thebluealliance.androidclient/cache/592a78e7b824550f7b0768ef84481c59.0.tmp to /data/data/com.thebluealliance.androidclient/cache/592a78e7b824550f7b0768ef84481c59.0
	at com.squareup.okhttp.internal.io.FileSystem$1.rename(FileSystem.java:85)
	at com.squareup.okhttp.internal.DiskLruCache.completeEdit(DiskLruCache.java:539)
	at com.squareup.okhttp.internal.DiskLruCache.access$2600(DiskLruCache.java:88)
	at com.squareup.okhttp.internal.DiskLruCache$Editor.commit(DiskLruCache.java:899)
	at com.squareup.okhttp.Cache$CacheRequestImpl$1.close(Cache.java:442)
	at okio.RealBufferedSink.close(RealBufferedSink.java:241)
	at com.squareup.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:956)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at retrofit.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:220)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
	at java.io.InputStreamReader.read(InputStreamReader.java:233)
	at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1300)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:5585)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:644)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
	at com.thebluealliance.androidclient.datafeed.retrofit.LenientGsonResponseBodyConverter.convert(LenientGsonResponseBodyConverter.java:32)
	at com.thebluealliance.androidclient.datafeed.retrofit.LenientGsonResponseBodyConverter.convert(LenientGsonResponseBodyConverter.java:17)
	at retrofit.OkHttpCall.parseResponse(OkHttpCall.java:148)
	at retrofit.OkHttpCall.execute(OkHttpCall.java:116)
	at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:111)
	at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:88)
	at rx.Observable$2.call(Observable.java:1162)
	at rx.Observable$2.call(Observable.java:1162)
	at rx.Observable.unsafeSubscribe(Observable.java:7710)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by phil-lopreiato** [comment]
Haven't seen this anymore, don't think this is a bug we can do anything about.
