### ISSUE TITLE
Firebase error IndexOutOfBoundsException

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#679]
On one phone, the PNCMP event's Ticker showed just "No items match the applied filter" even with nothing filtered out. Changing the filter didn't help. The refresh button didn't help.

Navigating to the week's Events and back seemed to fix it.

(See #672)

There are 8 `IndexOutOfBoundsException` errors like this in logcat:

```
04-07 17:00:29.453 25956 25956 E tba-android: Firebase error
04-07 17:00:29.454 25956 25956 W System.err: java.lang.IndexOutOfBoundsException: Invalid index 40, size is 28
04-07 17:00:29.454 25956 25956 W System.err: 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
04-07 17:00:29.454 25956 25956 W System.err: 	at java.util.ArrayList.add(ArrayList.java:147)
04-07 17:00:29.454 25956 25956 W System.err: 	at com.thebluealliance.androidclient.adapters.AnimatedRecyclerMultiAdapter.addItem(AnimatedRecyclerMultiAdapter.java:63)
04-07 17:00:29.455 25956 25956 W System.err: 	at com.thebluealliance.androidclient.adapters.AnimatedRecyclerMultiAdapter.applyAndAnimateAdditions(AnimatedRecyclerMultiAdapter.java:41)
04-07 17:00:29.455 25956 25956 W System.err: 	at com.thebluealliance.androidclient.adapters.AnimatedRecyclerMultiAdapter.animateTo(AnimatedRecyclerMultiAdapter.java:23)
04-07 17:00:29.455 25956 25956 W System.err: 	at com.thebluealliance.androidclient.fragments.FirebaseTickerFragment.lambda$updateList$11(FirebaseTickerFragment.java:462)
04-07 17:00:29.456 25956 25956 W System.err: 	at com.thebluealliance.androidclient.fragments.FirebaseTickerFragment.access$lambda$12(FirebaseTickerFragment.java)
04-07 17:00:29.456 25956 25956 W System.err: 	at com.thebluealliance.androidclient.fragments.FirebaseTickerFragment$$Lambda$13.call(Unknown Source)
04-07 17:00:29.456 25956 25956 W System.err: 	at rx.Observable$28.onNext(Observable.java:8192)
04-07 17:00:29.456 25956 25956 W System.err: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
04-07 17:00:29.457 25956 25956 W System.err: 	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:207)
04-07 17:00:29.457 25956 25956 W System.err: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-07 17:00:29.457 25956 25956 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
04-07 17:00:29.458 25956 25956 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-07 17:00:29.458 25956 25956 W System.err: 	at android.os.Looper.loop(Looper.java:148)
04-07 17:00:29.458 25956 25956 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5422)
04-07 17:00:29.458 25956 25956 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 17:00:29.459 25956 25956 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-07 17:00:29.459 25956 25956 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit
```

**Comment by nwalters512** [comment]
Interesting. Looks like that's a bug with some animation code I pulled from someone's SO answer. I'll look it.

**Comment by nwalters512** [comment]
I couldn't reproduce this, sadly. If it happens again, we can reopen this and I'll take another look.
