### ISSUE TITLE
java.lang.SecurityException while enabling myTBA

### ISSUE THREAD

**Issue by nwalters512** [the-blue-alliance/the-blue-alliance-android#720]
```
04-27 09:59:27.101 20362-20362/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.thebluealliance.androidclient, PID: 20362
                                                   java.lang.SecurityException: uid 10197 cannot explicitly add accounts of type: com.thebluealliance.androidclient.account.TBAACCOUNT
                                                       at android.os.Parcel.readException(Parcel.java:1620)
                                                       at android.os.Parcel.readException(Parcel.java:1573)
                                                       at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:890)
                                                       at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:712)
                                                       at com.thebluealliance.androidclient.accounts.AccountHelper.registerSystemAccount(AccountHelper.java:171)
                                                       at com.thebluealliance.androidclient.accounts.PlusHelper.onConnectCommon(PlusHelper.java:73)
                                                       at com.thebluealliance.androidclient.accounts.PlusManager.onConnected(PlusManager.java:164)
                                                       at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
                                                       at com.google.android.gms.common.api.internal.zzj.zzi(Unknown Source)
                                                       at com.google.android.gms.common.api.internal.zzh.zzpx(Unknown Source)
                                                       at com.google.android.gms.common.api.internal.zzh.onConnected(Unknown Source)
                                                       at com.google.android.gms.common.api.internal.zzl.onConnected(Unknown Source)
                                                       at com.google.android.gms.common.api.internal.zzc.onConnected(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzj$zzg.zzqL(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzj$zza.zzw(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzj$zzc.zzqN(Unknown Source)
                                                       at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dalianmao22233** [comment]
Hi did you fix this issue?  I met same one and may I ask how you solve it? 
Thanks!

**Comment by gregmarra** [comment]
Closing — the old myTBA auth flow was replaced with modern Google Sign-In via Firebase Auth. See [AuthModule.kt](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/main/app/src/main/kotlin/com/thebluealliance/android/di/AuthModule.kt).
