### ISSUE TITLE
NPE when resizing in freeform multi-window mode

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#770]
Android N's freeform multi-window mode is unfinished and buggy. E.g. tapping just outside an app's window can switch it to full-screen mode, then it's unclear how to get it back into a small window. Then tapping the zoom icon once or twice can crash the app with `java.lang.IllegalStateException: exitFreeformMode: You can only go fullscreen from freeform.`

Some normal window moving and resizing can also cause the app to crash. To reproduce:
- Create an Android N Nexus 10 AVD.
- Enable [freeform multi-window mode](http://stackoverflow.com/questions/35905726/how-do-we-try-freeform-multi-window-mode-on-the-android-n-developer-preview/38817283#38817283).
- Open TBA Android and another app in freeform mode.
- Try adjusting the position and size of TBA Android.

See the log, below. Note the second stack traceback has an empty `Rect(0, 0 - 0, 0)` and no TBA code on the stack. _That and the "fullscreen" error message suggests that Nougat will need bug fixes before device vendors enable multi-window mode._

But the first traceback has a NPE from this code:

```
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        // Forward the new configuration the drawer toggle component.
        mDrawerToggle.onConfigurationChanged(newConfig); // *** null mDrawerToggle here ***
    }
```

[Scroll to see the wide text -------->]

```
                                                                                   --------- beginning of crash
08-07 18:16:21.616 2715-2715/com.thebluealliance.androidclient.development E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                             Process: com.thebluealliance.androidclient.development, PID: 2715
                                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBarDrawerToggle.onConfigurationChanged(android.content.res.Configuration)' on a null object reference
                                                                                                 at com.thebluealliance.androidclient.fragments.NavigationDrawerFragment.onConfigurationChanged(NavigationDrawerFragment.java:379)
                                                                                                 at android.support.v4.app.Fragment.performConfigurationChanged(Fragment.java:2032)
                                                                                                 at android.support.v4.app.FragmentManagerImpl.dispatchConfigurationChanged(FragmentManager.java:2094)
                                                                                                 at android.support.v4.app.FragmentController.dispatchConfigurationChanged(FragmentController.java:255)
                                                                                                 at android.support.v4.app.FragmentActivity.onConfigurationChanged(FragmentActivity.java:287)
                                                                                                 at android.support.v7.app.AppCompatActivity.onConfigurationChanged(AppCompatActivity.java:156)
                                                                                                 at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4666)
                                                                                                 at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:4577)
                                                                                                 at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:4784)
                                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1597)
                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
08-07 18:16:21.627 1242-1809/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property

                                                 [ 08-07 18:16:21.656  1503: 2957 D/         ]
                                                 HostConnection::get() New Host Connection established 0x9c660040, tid 2957
08-07 18:16:21.658 2136-2958/com.google.android.gms D/DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
08-07 18:16:21.675 1503-2957/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
08-07 18:16:21.675 1503-2957/system_process D/OpenGLRenderer: Swap behavior 1
08-07 18:16:21.752 1503-1524/system_process E/ActivityManager: Received strange task bounds: Rect(0, 0 - 0, 0)
                                                               java.lang.Throwable
                                                                   at com.android.server.am.TaskRecord.validateBounds(TaskRecord.java:1612)
                                                                   at com.android.server.am.ActivityStackSupervisor.resizeTaskLocked(ActivityStackSupervisor.java:2250)
                                                                   at com.android.server.am.ActivityManagerService.resizeTask(ActivityManagerService.java:9386)
                                                                   at com.android.server.wm.TaskPositioner$WindowPositionerEventReceiver.onInputEvent(TaskPositioner.java:197)
                                                                   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                   at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                   at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                   at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by nwalters512** [comment]
Thanks for testing this out. I personally don't see any point in putting effort into fixing bugs caused by freeform mode until its behavior is finalized and stable. Our efforts should be invested in making sure we work well with split screen, which is very much stable and will be launching in the coming months.

**Comment by 1fish2** [comment]
Agreed. It's useful to know how un-ready it is.

[Techradar](http://www.techradar.com/us/news/phone-and-communications/mobile-phones/android-7-what-we-want-to-see-1311290) says, "The Android Nougat release date is happening in August".

[PC Advisor](http://www.pcadvisor.co.uk/new-product/google-android/android-nougat-70-uk-release-date-rumours-android-nougat-new-features-note7-download-preview-huawei-p9-friday-3628675/) says, "... Blass has since cleared up that he actually meant that when it launches in August it will include the August security patch."

**Comment by gregmarra** [comment]
Closing — the old Fragment/Activity architecture that caused this NPE was replaced entirely by a single-Activity Jetpack Compose app, which handles multi-window natively.
