### ISSUE TITLE
`INSERT INTO awards(name,enum,winners,year)` needs a key

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#779]
While running a debug build, run the script

    scripts/test_notification.py awards-posted

It sends a GCM to the client over adb. The client displays a notification but also logs a stack trace because a SQL constraint rejects an attempt to add the row to the DB without a `key`.

```
E/SQLiteLog: (1299) abort at 8 in [INSERT INTO awards(name,enum,winners,year) VALUES (?,?,?,?)]: NOT NULL constraint failed: awards.key
E/SQLiteDatabase: Error inserting name=Regional Chairman's Award enum=0 winners=[{"awardee":null,"team_number":2067},{"awardee":null,"team_number":78},{"awardee":null,"team_number":811},{"awardee":null,"team_number":2648}] year=2014
                  android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: awards.key (code 1299)
                      at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                      at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                      at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                      at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                      at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
                      at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
                      at com.thebluealliance.androidclient.database.ModelTable.add(ModelTable.java:44)
                      at com.thebluealliance.androidclient.database.ModelTable.add(ModelTable.java:69)
                      at com.thebluealliance.androidclient.database.writers.AwardListWriter.write(AwardListWriter.java:23)
                      at com.thebluealliance.androidclient.gcm.notifications.AwardsPostedNotification.updateDataLocally(AwardsPostedNotification.java:120)
                      at com.thebluealliance.androidclient.gcm.GCMMessageHandler.handleMessage(GCMMessageHandler.java:199)
                      at com.thebluealliance.androidclient.gcm.GCMMessageHandler.onHandleIntent(GCMMessageHandler.java:127)
                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.os.HandlerThread.run(HandlerThread.java:61)

```

The script's JSON data differs from what [the doc page says](https://www.thebluealliance.com/apidocs/webhooks) in that the `"event_key": "2014necmp",` property is at a different level of the data structure, but moving that field to match the doc causes

    com.google.gson.JsonParseException: Notification data does not contain 'event_key'

It seems the code is failing to include a DB key in the SQL INSERT.

**Comment by phil-lopreiato** [comment]
I just tried to repro this, and didn't get the error, so I think it's been fixed with the recent model/db updates
