### ISSUE TITLE
Tap a summary notification -> "The Blue Alliance Debug has stopped"

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#780]
Tapping a summary notification sometimes makes the app exit summarily. The OS displays a dialog "The Blue Alliance Debug has stopped" over the home screen.

There's no acknowledgement of the crash in logcat (!) even with filters turned off but Android Studio's Run view displays a stack traceback. The stack has no TBA code but it does have third party library code `io.nlopez.smartadapters`.

This occurs in the current master branch and also in the branch [issue_774](https://github.com/1fish2/the-blue-alliance-android/tree/issue_774) where I'm testing a fix for #774.

```
W/GAv4: Discarding hit. Missing tracking id parameter: a=1869011076,an=The Blue Alliance Debug,exd=NullPointerException (@DefaultBindableLayoutBuilder:viewType:38) {main},t=exception,sf=100.0,tid=,exf=1,aid=3.4.8-master.2+gd52ffe5,av=3.4.8-master.2+gd52ffe5
W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.thebluealliance.androidclient.development, PID: 3720
                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                      at io.nlopez.smartadapters.builders.DefaultBindableLayoutBuilder.viewType(DefaultBindableLayoutBuilder.java:38)
                      at io.nlopez.smartadapters.adapters.RecyclerMultiAdapter.getItemViewType(RecyclerMultiAdapter.java:134)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4664)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                      at android.view.View.layout(View.java:15671)
                      at android.view.ViewGroup.layout(ViewGroup.java:5038)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
                  	at android
E/GAv4: Successfully bound to service but never got onServiceConnected callback
Application terminated.
```

Steps to (sometimes) reproduce:

1. Start an Android API level 21 or later emulator.
2. Launch the app.
3. Tap the Back button to return to the home screen.
4. From a terminal window in the `the-blue-alliance-android/` directory, run `scripts/test_notification.py upcoming-match`. This should open a heads-up notification shade.
5. Wait for the notification shade to roll up. (This step might not be needed.)
6. Run `scripts/test_notification.py match-score`. This should open another heads-up notification shade.
7. Pull down the heads-up notification shade. This should reveal TBA's summary notification, "2 new notifications".
8. Tap on the summary notification's content area.

**Comment by 1fish2** [comment]
Here's a way to reproduce this crash. (Are there other ways?)

1. Uninstall the app. (Alternatively, it should suffice to clear out its recent notifications in the DB.)
2. Launch the app.
3. From the adb command line, do `scripts/test_notification.py district-points-updated`.
4. The app should display a district-points-updated notification. You can swipe it away.
5. Navigate to the app's Recent Notifications screen.  
--> _Boom._

In fact, `DistrictPointsUpdatedNotification.renderToViewModel()` returns `null`, and making it return a `GenericNotificationViewModel` does fix the crash.

The method is declared `@Nullable`. That seems to be inoperative.

`SummaryNotification.renderToViewModel()` returns `null` without causing a crash, but maybe some other code is careful to not add that one to a view model list.

**Comment by phil-lopreiato** [comment]
What's interesting is that `DistrictPointsUpdatedNotification` should never actually be sent by the server (it's only implemented on the client). Have you also encountered this crash in the wild?

**Comment by 1fish2** [comment]
I have not encountered this crash in the wild. So an alternate fix would be to remove that case from the app and the `test_notification.py` script.

BTW this `@Nullable` ought to propagate to somewhere that has to handle `null` properly, but it fails us.

**Comment by phil-lopreiato** [comment]
> BTW this @Nullable ought to propagate to somewhere that has to handle null properly, but it fails us.

Yeah, that's a bit worrying. Looks like that null check should happen [here](https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/binders/RecentNotificationsListBinder.java#L126)

**Comment by 1fish2** [comment]
That didn't fix it, but I did fix it and will send a PR.
