### ISSUE TITLE
NPE when a team has no name

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#842]
The 9000 series teams at MadTown Throwdown today lack team names. This causes at least one crash:

```
11-10 23:17:24.816  6133  6133 E AndroidRuntime: Process: com.thebluealliance.androidclient, PID: 6133
11-10 23:17:24.816  6133  6133 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
11-10 23:17:24.816  6133  6133 E AndroidRuntime:    at com.thebluealliance.androidclient.listitems.StatsListElement.getView(StatsListElement.java:45)
11-10 23:17:24.816  6133  6133 E AndroidRuntime:    at com.thebluealliance.androidclient.adapters.ListViewAdapter.getView(ListViewAdapter.java:29)
11-10 23:17:24.816  6133  6133 E AndroidRuntime:    at android.widget.AbsListView.obtainView(AbsListView.java:2372)
...
```

I'll send a PR.

**Comment by phil-lopreiato** [comment]
Nice find! I also updated APIv3 to provide a default value (since I'm pretty sure we treat team names as required), so it'll be best to have this fixed in both places
