### ISSUE TITLE
Adding to favorites crashes app

### ISSUE THREAD

**Issue by JonathanB05** [the-blue-alliance/the-blue-alliance-android#860]
When I browse to any team or event, click the star button, check any of the boxes, then press the done button, the app will crash.

I am running version 4.3.0 of the app on Android 7.0.

**Comment by JonathanB05** [comment]
When the app crashes, the Android Studio logger reports "[GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION"
It also gives this stack trace:

> E/UncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                      at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                      at java.lang.Thread.run(Thread.java:761)
                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.gson.JsonObject com.google.gson.JsonElement.getAsJsonObject()' on a null object reference
                                                      at com.thebluealliance.androidclient.datafeed.MyTbaDatafeed.updateModelSettings(MyTbaDatafeed.java:327)
                                                      at com.thebluealliance.androidclient.accounts.UpdateUserModelSettings.doInBackground(UpdateUserModelSettings.java:37)
                                                      at com.thebluealliance.androidclient.accounts.UpdateUserModelSettings.doInBackground(UpdateUserModelSettings.java:14)
                                                      at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                      at java.lang.Thread.run(Thread.java:761) 
03-26 18:18:24.428 527-662/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                               Process: com.thebluealliance.androidclient, PID: 527
                                               java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                   at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                   at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                   at java.lang.Thread.run(Thread.java:761)
                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.gson.JsonObject com.google.gson.JsonElement.getAsJsonObject()' on a null object reference
                                                   at com.thebluealliance.androidclient.datafeed.MyTbaDatafeed.updateModelSettings(MyTbaDatafeed.java:327)
                                                   at com.thebluealliance.androidclient.accounts.UpdateUserModelSettings.doInBackground(UpdateUserModelSettings.java:37)
                                                   at com.thebluealliance.androidclient.accounts.UpdateUserModelSettings.doInBackground(UpdateUserModelSettings.java:14)
                                                   at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                   at java.lang.Thread.run(Thread.java:761)`
